### ISSUE TITLE
Email-Backup 

### ISSUE THREAD

**Issue by sunnychuchu** [eworm-de/routeros-scripts#13]
That is great set of scripts, appreciate to all of your works .
The script contains a folder to organize backup file(s) . That is good idea but there are minor issue that is attached file contains the folder name. 

![image](https://user-images.githubusercontent.com/85664048/122158884-f1654580-ce9f-11eb-8add-e36d057ec024.png)

it is my person modification with daily backup and monthly backup, it will keep monthly and current date backup. 

# My modification sharing.

#Add type of backup
:local TypeOfBackup "";
:local mday [:pick $YYYYMMDD 6 8];
:if ($mday = "01") do={
  set $TypeOfBackup ("Monthly")
} else= { 
  set $TypeOfBackup ("Daily")
}

#Remove Outdate Backup file
/ file remove [ /file find where name~"^$0/.*.-$TypeOfBackup-.*\$"] 

#Rewrite File with date & time pattern 
:local FileName ([ $CharacterReplace ($Identity . "." . $Domain) "." "_"]."-".$TypeOfBackup."-". $YYYYMMDD . "-". $HHMMSS );

#Rewrite Subject Line with date & time pattern 
subject=([ $SymbolForNotification "floppy-disk,incoming-envelope" ] . \
    "Backup & Config"." ".$TypeOfBackup." ". $YYYYMMDD . " [" . [/system clock get time] . "]"); \

**Comment by eworm-de** [comment]
Well, the rationale with the directory is not to organize backups...
I started to use directories in `email-backup` and `upload-backup` to make sure the scripts do not conflict. E-mails are sent from queue now, thus the backup files have to be present after the script exited. Running `upload-backup` when the mail from `email-backup`  has not been flushed from queue could result in corrupted backups without directories.

However devices with low flash storage and/or RAM (depend on where the file are written to) are not uncommon with Mikrotik. That's why the scripts will clean up the files soon - already prepared in `next` branch.

Feel free to use the modified script on your devices, though.
